DELETE http://localhost:3003/api/blogs/6416a5349e708ed9b995bdd4
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkNhdCBIYXZlciIsImlkIjoiNjQxNTQ3YTZiOWJhZDZkNGI2NGU5MWFmIiwiaWF0IjoxNjc5MjAzMzkxfQ.w_5Kk0wG_9V7Si7rvO1xq5xlweRVaHLD2I6eld-R9Ko